### ISSUE TITLE
一加手机，调用记步模块抛了这个异常，能否请问下这个是什么原因吗？

### ISSUE THREAD

**Issue by yb12138** [jiahongfei/TodayStepCounter#12]
06-01 14:35:19.494 24062-24062/com.example.admin.sportapp W/System.err:     at com.example.admin.sportapp.activities.WalkActivity$TodayStepCounterCall.handleMessage(WalkActivity.java:137)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-01 14:35:19.982 24062-24062/com.example.admin.sportapp W/System.err: android.os.DeadObjectException
06-01 14:35:19.983 24062-24062/com.example.admin.sportapp W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:802)
        at com.today.step.lib.ISportStepInterface$Stub$Proxy.getCurrentTimeSportStep(ISportStepInterface.java:108)

**Comment by jiahongfei** [comment]
我试了一下 oneplusA5000没问题啊，都正常，你是demo，还是加到项目中了，你先运行一下demo看看好使吗

**Comment by yb12138** [comment]
跑了下demo没问题，我研究下是不是哪边冲突了。



1152042072@qq.com
 
发件人： 贾宏飞
发送时间： 2018-06-05 11:27
收件人： jiahongfei/TodayStepCounter
抄送： yb12138; Author
主题： Re: [jiahongfei/TodayStepCounter] 一加手机，调用记步模块抛了这个异常，能否请问下这个是什么原因吗？ (#12)
我试了一下 oneplusA5000没问题啊，都正常，你是demo，还是加到项目中了，你先运行一下demo看看好使吗

**Comment by jiahongfei** [comment]
下载最新代码试试
