### ISSUE TITLE
您好， 小米8不计步怎么回事！拿到的步数是0，列表都是"[]"。

### ISSUE THREAD

**Issue by FanChael** [jiahongfei/TodayStepCounter#38]
2020-07-18 10:03:32.936 1625-3851/? E/whetstone.activity: java.lang.NoSuchMethodException: com.android.server.am.ExtraActivityManagerService#getExecutingServicesSize(int)#exact
        at miui.util.ReflectionUtils.findMethodExact(ReflectionUtils.java:242)
        at com.miui.whetstone.server.WhetstoneActivityManagerService.isProcessExecutingServices(WhetstoneActivityManagerService.java:495)
        at com.miui.whetstone.server.IWhetstoneActivityManager$Stub.onTransact(IWhetstoneActivityManager.java:562)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by FanChael** [comment]
动态申请了权限ACTIVITY_RECOGNITION，获取到了[{"today":"2020-07-18","sportDate":1595038892,"stepNum":0,"km":"0.00","kaluli":"0.0"}]"，  但是一直都是这个。步数没有值1

**Comment by FanChael** [comment]
解决了。。就是权限问题。。不过一开始怎么走和甩都不动，突然动起来就好了。。这个一开始不灵敏是什么问题，大佬？
